spring.application.name=Placements_Management_Group-1
spring.datasource.url=jdbc:postgresql://localhost:5432/placements_group_db
spring.datasource.username=postgres
spring.datasource.password=5803
server.port = 8083